name: threads_search
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.2=pyhc872135_1
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - bs4==0.0.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - emoji==2.15.0
      - flask==3.1.2
      - greenlet==3.2.4
      - h11==0.16.0
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - numpy==2.2.6
      - outcome==1.3.0.post0
      - pandas==2.3.3
      - playwright==1.55.0
      - pyee==13.0.0
      - pysocks==1.7.1
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - selenium==4.38.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - trio==0.32.0
      - trio-websocket==0.12.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - wsproto==1.2.0
prefix: /opt/anaconda3/envs/threads_data
