name: threads_search
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - bs4==0.0.2
      - cachetools==6.2.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cssselect==1.3.0
      - cssutils==2.11.1
      - distro==1.9.0
      - emoji==2.15.0
      - flask==3.1.2
      - frozenlist==1.8.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - lxml==6.0.2
      - markupsafe==3.0.3
      - more-itertools==10.8.0
      - multidict==6.7.0
      - numpy==2.2.6
      - openai==2.8.1
      - outcome==1.3.0.post0
      - pandas==2.3.3
      - playwright==1.55.0
      - premailer==3.10.0
      - propcache==0.4.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyee==13.0.0
      - pysocks==1.7.1
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - selenium==4.38.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - tabulate==0.9.0
      - tiktoken==0.3.3
      - tqdm==4.67.1
      - trio==0.32.0
      - trio-websocket==0.12.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - wsproto==1.2.0
      - yagmail==0.15.293
      - yarl==1.22.0
prefix: /opt/anaconda3/envs/threads_search
